spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ing_server
    username: admin
    password: password
  jpa:
      hibernate:
          ddl-auto: update

logging:
  level:
    com:
      matthewa:
        restful-demo: DEBUG